# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: false
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: 7-Zip
      directives:
        description: Install 7-Zip
        allowPrerelease: false
      settings:
        id: 7zip.7zip
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: balenaEtcher
      directives:
        description: Install Balena Etcher
        allowPrerelease: false
      settings:
        id: Balena.Etcher
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Adobe Acrobat Reader DC (64-bit)
      directives:
        description: Install Adobe Acrobat Reader
        allowPrerelease: false
      settings:
        id: adobe.acrobat.reader.64-bit
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: bitwarden
      directives:
        description: Install Bitwarden
        allowPrerelease: false
      settings:
        id: Bitwarden.Bitwarden
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: TeraCopy
      directives:
        description: Install TeraCopy
        allowPrerelease: false
      settings:
        id: CodeSector.TeraCopy
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: K-Lite Codec Pack Standard
      directives:
        description: Install K-Lite Codec Pack
        allowPrerelease: false
      settings:
        id: CodecGuide.K-LiteCodecPack.Standard
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VLC media player
      directives:
        description: Install VLC media player
        allowPrerelease: false
      settings:
        id: VideoLAN.VLC
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: HandBrake
      directives:
        description: Install HandBrake
        allowPrerelease: false
      settings:
        id: HandBrake.HandBrake
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Corsair iCUE5 Software
      directives:
        description: Install Corsair iCUE
        allowPrerelease: false
      settings:
        id: Corsair.iCUE.5
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: CrystalDiskMark
      directives:
        description: Install CrystalDiskMark
        allowPrerelease: false
      settings:
        id: CrystalDewWorld.CrystalDiskMark.ShizukuEdition
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: CrystalDiskInfo
      directives:
        description: Install CrystalDiskInfo
        allowPrerelease: false
      settings:
        id: CrystalDewWorld.CrystalDiskInfo.ShizukuEdition
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Zotero
      directives:
        description: Install Zotero
        allowPrerelease: false
      settings:
        id: DigitalScholar.Zotero
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ElectronicArts.EADesktop
      directives:
        description: Install EA Desktop
        allowPrerelease: false
      settings:
        id: ElectronicArts.EADesktop
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: EpicGames.EpicGamesLauncher
      directives:
        description: Install Epic Games Launcher
        allowPrerelease: false
      settings:
        id: EpicGames.EpicGamesLauncher
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Google Drive
      directives:
        description: Install Google Drive
        allowPrerelease: false
      settings:
        id: Google.Drive
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Google Chrome
      directives:
        description: Install Google Chrome
        allowPrerelease: false
      settings:
        id: Google.Chrome
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Logitech G HUB
      directives:
        description: Install Logitech G HUB
        allowPrerelease: false
      settings:
        id: Logitech.GHUB
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: DirectX
      directives:
        description: Install DirectX
        allowPrerelease: false
      settings:
        id: Microsoft.DirectX
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: .NET Runtime 7
      directives:
        description: Install .NET Runtime 7
        allowPrerelease: false
      settings:
        id: Microsoft.DotNet.Runtime.7
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Microsoft PowerToys
      directives:
        description: Install Microsoft PowerToys
        allowPrerelease: false
      settings:
        id: Microsoft.PowerToys
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Visual Studio Code
      directives:
        description: Install Visual Studio Code
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Nexus Mods Vortex
      directives:
        description: Install Nexus Mods Vortex
        allowPrerelease: false
      settings:
        id: NexusMods.Vortex
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: NVIDIA GeForce Experience
      directives:
        description: Install NVIDIA GeForce Experience
        allowPrerelease: false
      settings:
        id: Nvidia.GeForceExperience
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: NVIDIA PhysX
      directives:
        description: Install NVIDIA PhysX
        allowPrerelease: false
      settings:
        id: Nvidia.PhysX
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Notepad++.Notepad++
      directives:
        description: Install Notepad++
        allowPrerelease: false
      settings:
        id: Notepad++.Notepad++
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Oracle Java Runtime Environment
      directives:
        description: Install Oracle Java Runtime Environment
        allowPrerelease: false
      settings:
        id: Oracle.JavaRuntimeEnvironment
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Speccy
      directives:
        description: Install Speccy
        allowPrerelease: false
      settings:
        id: Piriform.Speccy
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Python 3.11
      directives:
        description: Install Python 3.11
        allowPrerelease: false
      settings:
        id: Python.Python.3.11
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Anaconda3
      directives:
        description: Install Anaconda3
        allowPrerelease: false
      settings:
        id: Anaconda.Anaconda3
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: HWiNFO
      directives:
        description: Install HWiNFO
        allowPrerelease: false
      settings:
        id: REALiX.HWiNFO
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VNC Viewer
      directives:
        description: Install VNC Viewer
        allowPrerelease: false
      settings:
        id: RealVNC.VNCViewer
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Revo Uninstaller
      directives:
        description: Install Revo Uninstaller
        allowPrerelease: false
      settings:
        id: RevoUninstaller.RevoUninstaller
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Streamlabs.Streamlabs
      directives:
        description: Install Streamlabs
        allowPrerelease: false
      settings:
        id: Streamlabs.Streamlabs
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Valve Steam
      directives:
        description: Install Steam
        allowPrerelease: false
      settings:
        id: Valve.Steam
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WizTree
      directives:
        description: Install WizTree
        allowPrerelease: false
      settings:
        id: AntibodySoftware.WizTree
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WinSCP
      directives:
        description: Install WinSCP
        allowPrerelease: false
      settings:
        id: WinSCP.WinSCP
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: XIVLauncher
      directives:
        description: Install XIVLauncher
        allowPrerelease: false
      settings:
        id: goatcorp.XIVLauncher
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Spotify
      directives:
        description: Install Spotify
        allowPrerelease: false
      settings:
        id: Spotify.Spotify
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Deluge
      directives:
        description: Install Deluge
        allowPrerelease: false
      settings:
        id: DelugeTeam.Deluge
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Angry IP Scanner
      directives:
        description: Install Angry IP Scanner
        allowPrerelease: false
      settings:
        id: angryziber.AngryIPScanner
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Mozilla Firefox
      directives:
        description: Install Mozilla Firefox
        allowPrerelease: false
      settings:
        id: Mozilla.Firefox
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Amazon Kindle
      directives:
        description: Install Amazon Kindle
        allowPrerelease: false
      settings:
        id: Amazon.Kindle
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: CPU-Z AORUS
      directives:
        description: Install CPU-Z AORUS
        allowPrerelease: false
      settings:
        id: CPUID.CPU-Z.AORUS
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Discord
      directives:
        description: Install Discord
        allowPrerelease: false
      settings:
        id: Discord.Discord
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GitHub Desktop
      directives:
        description: Install GitHub Desktop
        allowPrerelease: false
      settings:
        id: GitHub.GitHubDesktop
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Git
      directives:
        description: Install Git
        allowPrerelease: false
      settings:
        id: Microsoft.Git
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: MSI Afterburner
      directives:
        description: Install MSI Afterburner
        allowPrerelease: false
      settings:
        id: Guru3D.Afterburner
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PotPlayer
      directives:
        description: Install PotPlayer
        allowPrerelease: false
      settings:
        id: Daum.PotPlayer
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Popcorn Time
      directives:
        description: Install Popcorn Time
        allowPrerelease: false
      settings:
        id: PopcornTime.Popcorn-Time
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Raspberry Pi Imager
      directives:
        description: Install Raspberry Pi Imager
        allowPrerelease: false
      settings:
        id: RaspberryPiFoundation.RaspberryPiImager
        source: winget
        InstallMode: silent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VMware Workstation Pro
      directives:
        description: Install VMware Workstation Pro
        allowPrerelease: false
      settings:
        id: VMware.WorkstationPro
        source: winget
        InstallMode: silent
  configurationVersion: "0.2.0"